name: yes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^4.0.6
  http_interceptor: ^1.0.2
  http_parser: ^4.0.1
  json_serializable: ^6.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  dropdown_button2: ^1.7.1
  flutter_blurhash: ^0.7.0
  # pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.1+1
  # firebase_core: ^1.20.0
  # firebase_messaging: ^12.0.1
  url_launcher: ^6.1.5
  infinite_scroll_pagination: ^3.2.0
  flutter_swiper: ^1.1.6
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_annotation: ^4.5.0
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
